// Generated by CoffeeScript 1.7.1
var devtools, gui, mapKeys, reload, win;

mapKeys = {
  116: 'f5',
  82: 'r',
  73: 'i',
  67: 'c',
  86: 'v'
};

gui = require('nw.gui');

win = gui.Window.get();

reload = function(event) {
  if (event.shiftKey) {
    return win.reloadIgnoringCache();
  } else {
    return win.reload();
  }
};

devtools = function(event) {
  if (win.isDevToolsOpen()) {
    return win.closeDevTools();
  } else {
    return win.showDevTools();
  }
};

window.document.onkeydown = function(event) {
  switch (mapKeys[event.which]) {
    case 'f5':
      return reload(event);
    case 'r':
      if (!event.metaKey) {
        return;
      }
      return reload(event);
    case 'i':
      if (event.metaKey && event.altKey) {
        return devtools(event);
      }
      if (event.shiftKey && event.ctrlKey) {
        return devtools(event);
      }
  }
};
